# User config
author: "monokēēbs"
tagline: "Custom  mechanical keybaords designed by jarv"
description: "soon™"
keywords: "monokēēbs, monokeebs, mechanical keyboards, 40% keyboards, 30% keyboards, small keyboards, little keyboards, keyboard, custom keyboard"
email: "pineapple@example.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "monokeebs"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed